services:
  front-end:
    build:
      context: .
      dockerfile: Dockerfile
    image: front-end-app:latest
    environment:
      - VITE_BACKEND_URL=https://localhost:443
    ports:
      - "80:80"
